const { logInService, oAuth2logInService, creatUService, userVerefication } = require("../services/users");
const { generate } = require("../utils/stringHelper");
const { autoDbSaver } = require("../services/autoDbSaver");

const userController = {
    /**
     * Стандартний логін (Email/Password)
     */
    logIn: async (req, res) => {
        try {
            const { email, password } = req.body;

            // Валідація на рівні контролера (професійніше використовувати Joi/Zod, але це вже гарний крок)
            if (!email || email.length < 3 || !password || password.length < 4) {
                return res.status(400).json({ message: "Invalid email or password format" });
            }

            const token = await logInService(email, password);
            await autoDbSaver();

            res.status(200).json({ access_token: token });
        } catch (error) {
            console.error("Login Error:", error.message);
            res.status(401).json({ message: error.message || "Authentication failed" });
        }
    },

    /**
     * Логін через Google OAuth2
     */
    OAuth2logIn: async (req, res) => {
        try {
            const { email, userName } = req.body;

            if (!email || email.length < 3) {
                return res.status(400).json({ message: "Valid email is required for Google OAuth" });
            }

            const token = await oAuth2logInService(email);
            res.status(200).json({ access_token: token });
        } catch (error) {
            res.status(500).json({ message: error.message });
        }
    },

    /**
     * Створення користувача через Google (якщо ще не існує)
     */
    creatUserWG: async (req, res) => {
        try {
            const { email, userName } = req.body;

            if (!email || !userName) {
                return res.status(400).json({ message: "Email and User Name are required" });
            }

            const autoGeneratedPassword = generate(12); // Генеруємо довший пароль для безпеки
            const newUser = await creatUService(email, userName, autoGeneratedPassword);

            return res.status(201).json(newUser);
        } catch (error) {
            res.status(500).json({ message: error.message });
        }
    },

    /**
     * Стандартна реєстрація нового користувача
     */
    creatNU: async (req, res) => {
        try {
            const { email, name, password } = req.body;

            if (!email || !name || !password) {
                return res.status(400).json({ message: "All fields (email, name, password) are required" });
            }

            const newUser = await creatUService(email, name, password);
            res.status(201).json(newUser);
        } catch (err) {
            res.status(500).json({ message: err.message });
        }
    },

    /**
     * Верифікація Email через токен
     */
    verefication: async (req, res) => {
        try {
            const { token } = req.query;

            if (!token) {
                return res.status(400).json({ message: "Verification token is missing" });
            }

            const isVerified = await userVerefication(token);

            if (isVerified) {
                return res.status(200).json({ success: true, message: "Email verified" });
            }
            
            throw new Error("Verification failed");
        } catch (error) {
            return res.status(403).json({ message: 'Invalid or expired token' });
        }
    }
};

module.exports = userController;